
export const SET_INITTAIL = 'SET_INITTAIL'
export const FETCH_USER_AUTH_SUCCCESS = 'FETCH_USER_AUTH_SUCCCESS'
export const FETCH_USER_AUTH_FAILED = 'FETCH_USER_AUTH_FAILED'
export const FETCH_USER_AUTH_LOADING = 'FETCH_USER_AUTH_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REQUEST_FETCH_SERVER = 'REQUEST_FETCH_SERVER'
